### ISSUE TITLE
Afloat working on Sierra, but causing app crashes.

### ISSUE THREAD

**Issue by chiehkuo** [w0lfschild/mySIMBL#10]
Thanks so much for your work on mySIMBL! I was so happy to have Afloat back! There's just one issue-- it seems to be causing other apps to crash, even System Preferences. Any idea how to fix this? Thanks!

**Comment by w0lfschild** [comment]
Hmm are you using the most recent version of Afloat? I'm not having any issues on my system. This would also be more of an Afloat issue than a mySIMBL one.

**Comment by thiagoveloso** [comment]
I works fine for me, even on Sierra's first update (10.12.1). I used Afloat's bundle from https://github.com/rwu823/afloat. Thanks @w0lfschild for the excellent work!

**Comment by thiagoveloso** [comment]
Ok, first issue detected: when Afloat is on, clicking zip files will never unzip them; instead it will call The Unarchiver preferences. This blocking issue had been reported here: https://github.com/rwu823/afloat/issues/34

**Comment by w0lfschild** [comment]
Closing this because it's not really a mySIMBL issue, also I can't replicate this.
