### ISSUE TITLE
Componant update dialog box unreadable on Mojave dark mode

### ISSUE THREAD

**Issue by uzegonemad** [w0lfschild/mySIMBL#100]
The component update dialog box is unreadable on Mojave dark mode.

Dark Mode:
![image](https://user-images.githubusercontent.com/430255/46497762-19d8ae80-c7e1-11e8-978a-02aa1486471c.png)

Light Mode for reference:
![image](https://user-images.githubusercontent.com/430255/46497778-23faad00-c7e1-11e8-9368-f9299db13ea6.png)

**Comment by ryanbahneman** [comment]
+1. I'm also experiencing this
