### ISSUE TITLE
DoctorDark theme: Menu bar icons gray

### ISSUE THREAD

**Issue by mdking117** [w0lfschild/mySIMBL#101]
I'm not sure if this is an issue with mySIMBL or with the DoctorDark theme, but with that theme enabled, certain menu icons are gray on gray.  See attached screen capture.  is there a way to change these icons to match the rest?
![doctordark enabled 2018-10-06 13-39-30](https://user-images.githubusercontent.com/21684359/46574269-9b117c00-c96e-11e8-904e-b2be8431aaad.jpg)

**Comment by w0lfschild** [comment]
It's an issue with a plugin, I don't know which one. If I recall correctly it might be FullscreenER that causes that but I don't remember.

Next time I get some free time I'll try to look into which plugin causes this.

**Comment by mdking117** [comment]
The only plugin that I'm using is the DoctorDark plugin.  Also, the font is flipped upside down.  That should probably be added as a new issue.  But here's what it looks like.
![monosnap 2018-10-07 17-15-14](https://user-images.githubusercontent.com/21684359/46587034-b1920300-ca54-11e8-8881-84c39cbd817e.jpg)

**Comment by gian8989** [comment]
Did you activate reduce transparency? I tried to use Doctor Dark in the past and this option was causing problems.
