### ISSUE TITLE
mySIMBLHelper still present after Uninstall

### ISSUE THREAD

**Issue by FabianStern** [w0lfschild/mySIMBL#102]
Dear w0lfschild,

I've tried since yesterday to fully uninstall mySIMBL, but unfortunately, the process mySIMBLHelper ist still running after startup. Since the uninstall script in the app package didn't work I manually deleted every program file from mySIMBL I could find and even re-installed MacOS Mojave. Please tell me how to fully remove the app without any remaining files/processes. That would help me a lot.

Cheers

**Comment by alextenczar** [comment]
> Dear w0lfschild,
> 
> I've tried since yesterday to fully uninstall mySIMBL, but unfortunately, the process mySIMBLHelper ist still running after startup. Since the uninstall script in the app package didn't work I manually deleted every program file from mySIMBL I could find and even re-installed MacOS Mojave. Please tell me how to fully remove the app without any remaining files/processes. That would help me a lot.
> 
> Cheers

Same issue, did you figure it out?

**Comment by FabianStern** [comment]
Fortunately it's gone now.
What I did was looking which files the mySimblHelper process does access using Activity Monitor, then deleting some of these (not the one which appear to be native macOS files) using Terminal in Mac Recovery (CMD + R on startup).

**Comment by meanmemes** [comment]
Anyone get a fix for this / list of files to delete? I'm having the same issue and I'm too scared to start deleting files on my own...👼

**Comment by w0lfschild** [comment]
This is the uninstall script:

``` bash

#!/bin/sh

function nukeFiles() {
    if [[ -e "$1" ]]; then
        if [[ -f "$1" ]]; then
            rm -v "$1"
        else
            rm -vr "$1"
        fi
    fi
}

function createFolder() {
	if [[ ! -e "$1" ]]; then
		mkdir -pv "$1"
	fi
	chmod 777 "$1"
}

log_dir="$HOME"/Library/"Application Support"/mySIMBL/logs
createFolder "$log_dir"
exec &>"$log_dir"/removeSIMBL.log
 
cleanupFiles=(
"/Library/Application Support/SIMBL"
"/Library/LaunchAgents/net.culater.SIMBL.Agent.plist"
"/Library/ScriptingAdditions/SIMBL.osax"
"/Library/ScriptingAdditions/EasySIMBL.osax"
"/System/Library/ScriptingAdditions/SIMBL.osax"
"/System/Library/LaunchAgents/net.culater.SIMBL.Agent.plist"
"$HOME/Library/ScriptingAdditions/SIMBL.osax"
"$HOME/Library/ScriptingAdditions/EasySIMBL.osax"
)

launchctl unload /Library/LaunchAgents/net.culater.SIMBL.Agent.plist
killall SIMBLAgent

echo "Removing files"

for i in "${cleanupFiles[@]}"; do
    echo Removing: "$i"
    nukeFiles "$i"
done

echo "Done"

```

**Comment by a-ten** [comment]
> This is the uninstall script:
> 
> ```shell
> #!/bin/sh
> 
> function nukeFiles() {
>     if [[ -e "$1" ]]; then
>         if [[ -f "$1" ]]; then
>             rm -v "$1"
>         else
>             rm -vr "$1"
>         fi
>     fi
> }
> 
> function createFolder() {
> 	if [[ ! -e "$1" ]]; then
> 		mkdir -pv "$1"
> 	fi
> 	chmod 777 "$1"
> }
> 
> log_dir="$HOME"/Library/"Application Support"/mySIMBL/logs
> createFolder "$log_dir"
> exec &>"$log_dir"/removeSIMBL.log
>  
> cleanupFiles=(
> "/Library/Application Support/SIMBL"
> "/Library/LaunchAgents/net.culater.SIMBL.Agent.plist"
> "/Library/ScriptingAdditions/SIMBL.osax"
> "/Library/ScriptingAdditions/EasySIMBL.osax"
> "/System/Library/ScriptingAdditions/SIMBL.osax"
> "/System/Library/LaunchAgents/net.culater.SIMBL.Agent.plist"
> "$HOME/Library/ScriptingAdditions/SIMBL.osax"
> "$HOME/Library/ScriptingAdditions/EasySIMBL.osax"
> )
> 
> launchctl unload /Library/LaunchAgents/net.culater.SIMBL.Agent.plist
> killall SIMBLAgent
> 
> echo "Removing files"
> 
> for i in "${cleanupFiles[@]}"; do
>     echo Removing: "$i"
>     nukeFiles "$i"
> done
> 
> echo "Done"
> ```

Whenever I run that script it will never finish. And my simblagent still runs at startup.  I'm running it as a .command file.  That should work right?

**Comment by w0lfschild** [comment]
You would need to run it as root and SIP also has to be off.

**Comment by a-ten** [comment]
> You would need to run it as root and SIP also has to be off.

Thank you for clarifying, I was expecting the terminal to echo done but I found the log file of the uninstallation.  Thanks!

**Comment by jacobidiego** [comment]
Hi.
I have lurked the web to uninstall this software that was popping up every second for every app, until I learned that is not compatible with SIP.
Mojave 10.14.5
SIMBL 0.7.5

**mySIMBLHelper wont uninstall.**

I have disabled SIP with :
[quote] Boot into Recovery mode: Restart and hold cmd+r
In Menu -> Toolings -> Start “Terminal”
$ csrutil disable; reboot[/quote]
[quote] and change to "enable" to re-enable SIP[/quote]

Then as root, executed the script with "sudo" and verified the log file.
After relogging, rebooting, restarting in safe mode to delete temps, it is still running.

If I try to close it will inmediatelly restart.
Files opened by it refers to 2 temporal location that are rather permanent.
[quote]"$HOME/Library/Caches/org.w0lf.mySIMBLHelper"
"/private/var/folders/tl/*/T/AppTranslocation/*/d/mySIMBL.app"[/quote]

For the case of the private folder, there is something like a mounted file that can not be delete by means of "rm" it contains a copy of the mySIMBL.
If I try to unmount it, it will inmediatelly regenerate with another encoded folder name.

Is it possible to uninstall this?
Do I have to learn how to fully reinstall a MAC?

**Comment by jacobidiego** [comment]
Ok.. So I found the way myself.
The next are all the files that need to be added to the script.
I deleted them manually, so I am not sure if it will work without editing.

With this, mySIMBLHelper stoped starting and all the dumpstate shown with by launchctl.
Hope it helps.

"$HOME/Library/Caches/org.w0lf.mySIMBLHelper"
"/private/var/folders/tl/*/T/AppTranslocation/*/d/mySIMBL.app"
"/private/var/folders/tl/*/C/org.w0lf.mySIMBLHelper"
"$HOME/Library/Preferences/org.w0lf.mySIMBL.plist"
"$HOME/Library/Preferences/org.w0lf.mySIMBLHelper.plist"
"$HOME/Library/Caches/org.w0lf.mySIMBLHelper"

**Comment by albertputinjobs** [comment]
try these commands to completely remove it launchctl list | egrep {SIMBLAgent} and launchctl remove {SIMBLAgent}
