### ISSUE TITLE
Uninstall Issues

### ISSUE THREAD

**Issue by mo4ya2000** [w0lfschild/mySIMBL#104]
Even though I use the uninstall I still had to remove the app separately. I've done that but SIMBLAgent.app stays in the activity log as running and every time I open an app it keeps wanting permission.  How do I remove this off of my macbook air on OSX Mojave ?

**Comment by meanmemes** [comment]
Same issue here... macbook pro Mojave

**Comment by cryptosmoka** [comment]
Same problem, very frustrating

**Comment by anatoliykmetyuk** [comment]
Same issue. Especially given the fact that on the newer versions of Mac, it constantly bombards me with popups requesting access to various apps. What do I do?

**Comment by anatoliykmetyuk** [comment]
This command worked for me:

```
sudo rm -r "/Library/Application Support/SIMBL/SIMBLAgent.app/Contents/MacOS/SIMBLAgent"
```

Which is quite strange: although `/Library/Application Support/SIMBL/` folder did not exist on my machine, the command successfully deleted the above file and, after manually killing the process afterwards, it did not respawn again.

**Comment by cryptosmoka** [comment]
For me this doesn't solve the problem.  Keeps asking for annoying permissions.  Using uninstall in mySimbl doesn't do anything.  Throwing Mysimbl in the bin doesn't do anything to the permissions either.

**Comment by npyl** [comment]
Run this script:

```sudo /Applications/mySIMBL.app/Contents/Frameworks/SIMBLManager.framework/Versions/A/Resources/removeSIMBL```

**Comment by npyl** [comment]
As I understand from this [post](https://github.com/w0lfschild/mySIMBL/issues/102), mySIMBL contains a script that uninstalls all the components, but for some reason it is not being run with administrator privileges as it should... To fix this, run the script yourself using sudo as I showed in the previous comment.

**Comment by w0lfschild** [comment]
I'm guessing the script is maybe failing because SIP is on? The thing is that the agent is outside of SIP restricted areas and one file failing to remove shouldn't kill the script.

I think I'm going to switch to a .pkg installer and uninstaller.

**Comment by semiopat** [comment]
Hi w0lfschild
I'm having the same problem mentioned here since I move to Mojave with my new macbook pro. I desinstall and reinstall MySimbl but nor I can't run ColorSideBar, neither I got the annoying prompt on any app opening. Do you plan to release a .pkg soon ?

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/mySIMBL/issues/64#issuecomment-346915057
