### ISSUE TITLE
This repository has been disabled. Access to this repository has been disabled by GitHub staff

### ISSUE THREAD

**Issue by MirzayevFarid** [w0lfschild/mySIMBL#108]
I am getting this page when I try to access Latest updates page in order to install any app:
This repository has been disabled.
Access to this repository has been disabled by GitHub staff. Contact support to restore access to this repository.

**Comment by nihilus** [comment]
Yeah, it's a pity the guy went MIA...

**Comment by npyl** [comment]
Hey guys isn't [this](https://github.com/w0lfschild/mySIMBL/releases) what you need?

**Comment by WoLpH** [comment]
> Yeah, it's a pity the guy went MIA...

Who are you referring to? @w0lfschild still seems to be active.

I don't see that error over here btw, perhaps it was temporary? Or do you have a link to it?

**Comment by npyl** [comment]
[app_updates](https://github.com/w0lfschild/app_updates) seems to be back.

**Comment by npyl** [comment]
[app_updates](https://github.com/w0lfschild/app_updates) seems to be back online.
