### ISSUE TITLE
Plugins fail to load on 10.12.2 Beta (16C63a)

### ISSUE THREAD

**Issue by saagarjha** [w0lfschild/mySIMBL#11]
It looks like mySIMBL has a hard time injecting code in build 16C63a–none of my plugins are loaded, even after pressing "Inject into running applications".

**Comment by w0lfschild** [comment]
I'm not having this issue maybe try restarting. Are there any more details you can give?

**Comment by saagarjha** [comment]
Restarting appears to partially fix the issue–most of the plugins load this time (except for Flashlight, but that's probably not related). I am, however, having issues installing new plugins, i.e. they aren't actually installed when I click "Install".

**Comment by w0lfschild** [comment]
Go all the way into the bundle page and install from there. The grayed out install button in the source view is not enabled right now.

**Comment by saagarjha** [comment]
It looks like mySIMBL isn't copying the bundles to `/Library/Application Support/SIMBL/Plugins` when I open them. Manually copying the bundle to the directory works, however.

**Comment by w0lfschild** [comment]
@saagarjha 

Not copying bundles when you install them from a source or ones you're opening with mySIMBL?
What are the permissions of `/Library/Application Support/SIMBL/Plugins` for you?

**Comment by saagarjha** [comment]
They're `drwxrwxr-x  12 root  wheel  408` on my machine. Should they be something else?

**Comment by w0lfschild** [comment]
The `-` should be a `w`.

**Comment by w0lfschild** [comment]
Try version 0.4.1

Also might as well run `chmod 755 /Library/Application Support/SIMBL/Plugins`

**Comment by derimagia** [comment]
All of the folders in and including /Library/Application Support/SIMBL are 777 for me. It makes me a little uneasy of having a folder in root library that loads plugins like this be set to that. I'm sure it's required by can you add an explanation somewhere?

**Comment by w0lfschild** [comment]
Yeah that's understandable. It might work with 775 or something else. I think you could lock it down if you want but then you'd have to manually manage all your plugins. 

I don't want the program to have to ask for admin permissions just to toggle the state of a plugin. If someone has a solution for that while keeping tighter permission I would gladly implement that.
