### ISSUE TITLE
Uninstall SIMBL in README.md needs changes

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [w0lfschild/mySIMBL#112]
The `README.md` says

> Select `SIMBL` from the sidebar, then click `uninstall SIMBL`. Log out and back in for changes to fully apply.

However, as of mySIMBL 0.71, there is no `SIMBL` in the sidebar. I'd suggest change this as follows:

Select **`System Info`** from the sidebar, then click **`Uninstall SIMBL`**. Log out and back in for changes to fully apply.

(Capital U)

<img width="842" alt="Screen Shot 2019-06-01 at 7 33 49" src="https://user-images.githubusercontent.com/6400352/58744842-1cf36f80-8440-11e9-86df-4c32968e6280.png">

**Comment by w0lfschild** [comment]
Done, thanks.
