### ISSUE TITLE
Uninstall button does not work

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [w0lfschild/mySIMBL#113]
`Uninstall SMIBL` button failed in mySIMBL 0.71 on macOS 10.14.5.

#64 and #35 are related, but they didn't report the failure of the button. So I consider this as potentially a separate issue.

<img width="532" alt="Screen Shot 2019-06-01 at 7 44 10" src="https://user-images.githubusercontent.com/6400352/58744948-9b044600-8441-11e9-9c34-4559b9a9a5e7.png">

**Comment by w0lfschild** [comment]
Yup for whatever reason that uninstall button kind of sucks 👎 

I'd guess most failures have to do with the user trying to run the uninstall with SIP enabled.

Not gonna lie in saying I'm not gonna try to add any extra warning windows or anything beyond the existing failure message as this project has been replaced with [MacForge](https://github.com/w0lfschild/MacForge).
