### ISSUE TITLE
mySIMBL needs to update some components on your system

### ISSUE THREAD

**Issue by SuicinivSucram** [w0lfschild/mySIMBL#115]
Every time mySIMBL show me this message "mySIMBL needs to update some components on your system..." and no work

**Comment by w0lfschild** [comment]
Hmm, do you have SIP on?

Also this project is discontinued, If you're using 10.11 or above you should check out [MacForge](https://github.com/w0lfschild/MacForge). I eventually plan to have mySIMBL offer to replace itself with MacForge in an update.
