### ISSUE TITLE
"latest" mySIMBL gets latest MacForge

### ISSUE THREAD

**Issue by TallTed** [w0lfschild/mySIMBL#119]
I realize this is discontinued, but I'm hoping that a couple minor tweaks to the Github project will make me (and probably others) happy without any need to change code.

I just found patched versions of the primary tools that kept me trapped on Yosemite, and gleefully updated to El Capitan, only to find that mySIMBL and SafariStand weren't working, though both claim compatibility with Safari 11 and macOS 10.11...

What to do?  Check for updated versions, just in case there was a dot-release I'd missed...

Turns out, I have mySIMBL 0.7.2 -- which is later than the latest "version" but earlier than what *appears* to be the latest in the code directory...  I'm hoping there's something between mySIMBL 0.7.2 and MacForge 0.14.2 that might get me back to happiness.

Can you help me out?

**Comment by w0lfschild** [comment]
Being totally honest:
I have no idea what's in the 0.8.1 commit that's here on GitHub.
I also have no idea what plugin works with what version of such and such software or macOS 
I also have no idea what macOS version works or don't work with older versions of this project but the readme should be true

mySIMBl version history : https://github.com/w0lfschild/app_updates/tree/master/mySIMBL
Safari Stand : https://github.com/anakinsk/SafariStand

_**If you're truly using macOS 10.11 you should NOT be using SAFARI**_ and instead use any other browser that can still receive security updates such as Firefox, Brave, Chrome, etc...

Also you should brace yourself for the fact that SafariStand is dead and never coming back so you will have to adapt your workflow at some point, if not now then whenever your computer breaks. Browsers like Firefox and Chrome support rich extensions which may be able to give said browsers some or all of the features you use in SafariStand.

**Comment by TallTed** [comment]
All good. Thanks for your past efforts.

I use Chrome and Safari and Opera and Brave and others for different purposes. My primary use of SafariStand has long been the tab-list window. I'll suffer some but survive if I can't figure out how to revive it.
