### ISSUE TITLE
mySIMBL 0.4.2 works only when manually loading plugins

### ISSUE THREAD

**Issue by brianfos** [w0lfschild/mySIMBL#13]
I just upgraded to v0.4.2 of mySIMBL (I had been using 0.3.1). My plugins work ONLY when I open mySIMBL and click on "Load into all running applications." Otherwise, nothing happens on Restart. You might note that SIMBLAgent is a valid login item (which I figured would load the plugins upon startup). The SIMBLAgent version number is 1.5.4. I am running Mac OS X 10.10.5 (Yosemite). and have the following plugins in mySIMBL:

cDock
colorfulSidebar9
NotificationClear
safariSoda
TheLostFinderNewWindow

Until I discovered v0.4.2 yesterday, I had been running v0.3.1 with only ColorfulSidebar 1.1.2 (from another developer, not the "9" version) and TheLostFinderNewWindow for quite a few months.

Do you have any thoughts or ideas?

**Comment by w0lfschild** [comment]
Try 0.4.3 I think I've fixed the issue.

**Comment by brianfos** [comment]
YES! Thank you!!! Everything loads correctly under v0.4.3.

Now, if you really want to make something even better, look into TheLostFinderNewWindow. Its development has been stopped, although source code is provided. It restores opening Finder windows in a new window instead of opening in the same window (the default for Macs for decades until Apple decided Macs should dumb down and emulate iPhones). However, it does NOT provide for the option-key override, which would allow for opening a window in the same window (which is the current Mac OS default). If you could build in the option-key functionality, then I'd almost have my Mac operating as functionally as I used to.

Unless you're REALLY adventurous and could restore arrows at the end of scroll bars, which are really critical for applications like Microsoft Excel. Or, for making the green "zoom" Finder button zoom the window to the needed non-menubar size of the window instead of putting it in full-display preview mode. OK, now I am dreaming....

Here's the website for TheLostFinderNewWindow:

http://siggi.hk/index.php?action=TheLostFinderNewWindow

**Comment by w0lfschild** [comment]
@brianfos 

> Now, if you really want to make something even better, look into TheLostFinderNewWindow...

Not sure what exactly it is you want the Finder to be doing? Are you talking about `right click > open in new tab` having reversed functionality?

> Unless you're REALLY adventurous and could restore arrows at the end of scroll bars...

Why not just use the arrow keys?

> Or, for making the green "zoom" Finder button zoom the window...

 Already made that: https://github.com/w0lfschild/fullscreenER

**Comment by brianfos** [comment]
What TheLostFinderNewWindow does is restore the Finder window-opening behavior to what it had been for decades, namely when you double-click on a folder, it opens up its contents in a new folder, leaving the original folder behind it. Starting somewhere in OS X 10.10 or perhaps before, when you double-click on a folder in the Finder, the Finder window replaces the original folder with the new one, so you can’t immediately go back to the original one. TheLostFinderNewWindow makes the Finder open up windows in new folders. That’s what I want to happen 90% of the time, and that is what TheLostFinderNewWindow  does. However, there are a few times when I want the Finder window to replace the contents of the original Finder window with the one just opened (that’s the only option with 10.10 and above). In old Mac OS’s, you could invoke that behavior by holding down the option key when double-clicking on a Finder window. That optional functionality is missing from TheLostFinderNewWindow.

As to your second point, pressing the arrow keys, that does not do it. If I want to show a client a specified area of my Excel spreadsheet on screen and then slowly move it one row or column at a time, I have to carefully negotiate the scroll bar. Yes, if the cursor happens to be selected in a cell at the outside edges of a window, it will scroll over, but I don’t always have the extreme cell selected. Furthermore, if I have merged cells, then I can get behavior I don’t want. There’s a reason that scroll bar arrows existed in the first place: they provide valuable functionality. The only reason that Apple took them out is to make Mac windows dumb down to the level of iPhones.

Finally, I will look into fullscreenER to see if it does the trick (although this one is my least important of functional desires).

Thank you so much for listening to what I have to write and for pointing me to fullscreenER!!!!

Brian A. Foster
brianfos@ix.netcom.com

**Comment by w0lfschild** [comment]
So you want each time you double click a folder for Finder to open a new window with that folders contents?

If that's what you want just go to `Finder > Preferences > General` and uncheck `Open folders in tabs instead of new windows`.

**Comment by brianfos** [comment]
Nope. That’s doesn’t work. What it does is open up the contents in a folder instead of a new tab, but the folder is the same folder as the original, not a second new Finder window above the original Finder window. If you’ve used a Mac for years, you know that double-clicking on a folder usually opened up a new folder on top of the old one, and you could see the original one below, move items among folders, etc. Under 10.10 and above, what you get is the exact same Finder window, but the contents of the just opened folder appear in the window: you get just one Finder window open instead of two.

Brian A. Foster
brianfos@ix.netcom.com

**Comment by rafalenden** [comment]
I'm having the same issue with the newest version of mySIMBL.

OS: Sierra 10.12.2
MySIMBL: 0.4.3
spotifyPlus: 0.6.0

**Comment by michaelhood** [comment]
Same as @rafalenden, 0.4.3 (downloaded from [here](https://github.com/w0lfschild/app_updates/raw/master/mySIMBL/mySIMBL_master.zip) a few minutes ago.)

No previous install of anything SIMBL on this machine.

OS: 10.12.1
MySIMBL: 0.4.3
SIP: Disabled

**Comment by w0lfschild** [comment]
Is this working now in version 0.5.3?

**Comment by rafalenden** [comment]
Yes, it's working great in 0.5.3. Thank you!

**Comment by iphonecaptain** [comment]
I'm new to MySimbl can anyone help me understand how I get typestatus working on Mac.  I know this thread is about Simbl but its basically whats preventing me from getting this going I think.  Do I choose to load into all applications??/ . I been trying to get this working hours.  I just contacted the dev and he stated he didn't know how and I would have to wait until an update releazed.  I wanting to show a tut on YT for this so I will share yourt twitter info too if thats ok

**Comment by iphonecaptain** [comment]
It also shows under the manage section too.  I have  question about this??  Do I choose the green tab or yellow

**Comment by artazol** [comment]
Downloaded mySIMBL 0.7.0 and installing plugins not working.

OS: High Sierra 10.13.4
MySIMBL: 0.7.0
