### ISSUE TITLE
fullscreenER 1.1.1 buggy

### ISSUE THREAD

**Issue by brianfos** [w0lfschild/mySIMBL#14]
I'm using fullscreenER 1.1.1 in OS X 10.10.5 (Yosemite), and it's making my open/save dialog boxes almost nonfunctional. They will not respond to any clicking by the mouse, although they will respond to keys typed on the keyboard, including (fortunately), the Esc key. It may be a dynamic with DefaultFolder X v5.1.1, which I am also using, but I did not have time to zero in on the possible interaction.

**Comment by w0lfschild** [comment]
Probably not gonna fix specific interactions like that.
