### ISSUE TITLE
Use mySIMBL-Plugins while SIP is enabled

### ISSUE THREAD

**Issue by Askern** [w0lfschild/mySIMBL#15]
Hello,

Is there any way to use the mysimbl plugins while the SIP is enabled again (after installing MYSIMBL and all of the plugins successfully after disabling the SIP)?. To be precise I want to use the Plugin Safaristand in this way later. (Safari 10, OS X El Cap, latest Version).

Thank you!

**Comment by w0lfschild** [comment]
Yes you can turn SIP back on after SIMBL is installed. Its possible that a future update may require it to be disabled again to update the SIMBL.osax bundle but aside from that you can continue to use mySIMBL with SIP off, it only needs to be turned on to install SIMBL.osax.

**Comment by Askern** [comment]
Yes I can use MySIMBL while SIP is turned off without any problems! The problem is that I cannot use Safaristand  (https://github.com/anakinsk/SafariStand) while SIP is turned off.

**Comment by w0lfschild** [comment]
Dunno what the issue is, could be SafariStand if other plugins are working for you.

Might also just try running this command in terminal after you open Safari
`osascript -e "tell application \"Safari\" to inject SIMBL"`

**Comment by Askern** [comment]
When I enter the command I get an error.

"29:41: execution error: „Safari“ hat einen Fehler erhalten: Die Zugriffsrechte wurden verletzt. (-10004)"

**Comment by Askern** [comment]
I found it out: Under OS X Sierra and Safari 10 it is possible to enable SIP again and to use Safaristand. In OS X El Cap under Safari 10 it is not possible to possible to use Safaristand after enabling SIP again. Thank you all for your help!

**Comment by Askern** [comment]
I found it out: Under OS X Sierra and Safari 10 it is possible to enable SIP again and to use Safaristand. In OS X El Cap under Safari 10 it is not possible to possible to use Safaristand after enabling SIP again. Thank you all for your help!
