### ISSUE TITLE
Resizable Frames on Taskbar Icons?

### ISSUE THREAD

**Issue by mkormendy** [w0lfschild/mySIMBL#16]
Ever since I installed mySIMBL and disabled SIP on Mac OS X Sierra (latest version), I've been having taskbar issues with certain applications. (Optimal Layout for example).

Well today, I accidentally grabbed the edge of one of the taskbar icons instead of the window to resize it, and miraculously I was able to resize the boundaries of the taskbar icon application.

See the attached gif below:

![macos-taskbar-icons-resize-frames](https://cloud.githubusercontent.com/assets/1437667/21644516/64648a30-d253-11e6-97b1-c851592dc988.gif)

Possible bug? I have SpotlightSIMBL and fullscreenER installed and running only.

**Comment by w0lfschild** [comment]
Are you using the latest version of fullscreenER?

**Comment by mkormendy** [comment]
Apologies, yes the latest version of fullscreenER fixes the issue. Thank you!

**Comment by w0lfschild** [comment]
No problem, glad it's working now.
