### ISSUE TITLE
How to install SIMBL?

### ISSUE THREAD

**Issue by J5011** [w0lfschild/mySIMBL#17]
Hi, starting mySIMBL gets always this answer on top:

SIMBL Manager has determined that SIMBL ist not
installed or outdated on your system.
This means that applications and plugins which
require SIMBL to function will likely not work.
	[Cancel]	[Install]

After pushing [Install] the response is

SIMBL install failed!
Something went wrong, probably System Integrity
Protection.

So, how to install SIMBL on Mac OS 10.11.6?

Kind regards
Jobst

**Comment by fnankivell** [comment]
Have you turned off System Integrity Protection?

http://www.macworld.co.uk/how-to/mac/how-turn-off-mac-os-x-system-integrity-protection-rootless-3638975/

**Comment by J5011** [comment]
Good evening,

Thank you very much for your help. I thought that the program mySIMBL shows the instruction for turning off SIP,
but unfortunately there was an other field in front, so that the instructions were not to read. And clicking a button
both fields disappeared. Perhaps you can alter this.



With your link I could follow the instructions and everything works fine now.

Kind regards
Jobst

Jobst & Beate Flasbart
83 Watergang Straat
Aan de Weber Estate
Jamestown / Stellenbosch 7600
South Africa

Email: jobst.flasbart@gmx.de
Cell Jobst: 076 911 4600
Email: beate.flasbart@gmx.de
Cell Beate: 072 639 5220

**Comment by zippyx17** [comment]
I turned off system integrity protection in the terminal in the cmd+r bootup, by typing "csrutil disable" and it said it was disabled. However, when I restart my computer it is still on.
