### ISSUE TITLE
Feat request: apps subfolder index

### ISSUE THREAD

**Issue by waxfingers** [w0lfschild/mySIMBL#19]
Seems mySIMBL won't list aplications (blacklist function) located within Aplications/user's subfolders. For 1 or 2 apps it can be fixed with a symlink but when there are many it's messy. Maybe mySIMBL could also lookup the folders in aplications' sublevels. Thank you  =)

**Comment by waxfingers** [comment]
Thanks so much Wolfgang, with 0.5.1 now works perfectly 
😃

**Comment by w0lfschild** [comment]
Awesome. Glad it's working for you.
