### ISSUE TITLE
Problem with TypeStatus v1.0 on mySIMBL 0.4.3

### ISSUE THREAD

**Issue by nschenone** [w0lfschild/mySIMBL#20]
I just installed mySIMBL 0.4.3 as well as TypeStatus 1.0. I'm on macOS 10.12.1. The plugin only worked at first when I manually load it using "Load into all running applications," but then it stopped working all together. I've tried restarting both applications as well as pressing the "load" button before, during, and after loading the targeted app.

Thanks!

**Comment by nschenone** [comment]
False alarm, sorry about that. I re-enabled System Integrity Protection. I'm not sure whether that or the subsequent reboot fixed the problem, but everything is working now. Thanks!

**Comment by w0lfschild** [comment]
Glad it sorted itself out.
