### ISSUE TITLE
v0.5.1 & v0.5.2 updates are totally messed up

### ISSUE THREAD

**Issue by JayBrown** [w0lfschild/mySIMBL#21]
The update to v0.5.1 went well, but after launching the new version, the app froze, while asking to update SIMBL. I had to force-quit the app, then launch it again, and all of a sudden it was asking to update to v0.5.2. (Which v0.5.2?! It's not here on GitHub.) The whole thing then hung during installation (v0.5.2 update). I tried to force-quit all SIMBL and mySIMBL-related processes, which didn't work, and the mySIMBL icon in the Dock was still showing the app as running, even though it wasn't in top or ps aux. Couldn't even log out of my user account, because OS X wasn't able to quit the app either. So I had to do hard reboot. I then downloaded the v0.5.1 from GitHub, installed it manually, then the app froze again (see above), then again a force-quit and relaunch, and now I was able to update SIMBL. I'm ignoring the in-app update to v0.5.2 for now, and will install it manually, as soon as it's available for download, because the whole update system doesn't seem to work properly with mySIMBL.

**Comment by w0lfschild** [comment]
Maybe it's a bad plugin freezing mySIMBL?

Either way a new version [0.5.3](https://dl.devmate.com/org.w0lf.mySIMBL/29/1485491280/mySIMBL-29.zip) is out.

**Comment by michel-slm** [comment]
@w0lfschild could the new versions be tagged / marked as releases on GitHub? The latest I see here is 0.2
