### ISSUE TITLE
mySIMBL 0.5.1 doesn't update to 0.5.2

### ISSUE THREAD

**Issue by herbs** [w0lfschild/mySIMBL#22]
Howdy,

Every time I start up 0.5.1 it says 0.5.2 is available but it can't install it.

Good Luck,
herbs2

**Comment by w0lfschild** [comment]
0.5.2 wasn't supposed to be up that was just some testing I was doing and should be gone now.

**Comment by w0lfschild** [comment]
Should be fixed now.
