### ISSUE TITLE
mySIMBL.app doesn't work with colorfulsidebar in Sierra

### ISSUE THREAD

**Issue by thewhitedog** [w0lfschild/mySIMBL#23]
I'm trying the latest version of mySIMBL: 0.5.1 on Jan 26, 2017. The only SIMBL plugin I'm interested in using is colorfulsidebar and it doesn't work. In the past, in OS X 10.9.5, it required relaunching the Finder to get colorfulsidebar to work. Now, in macOS X 10.12.2, relaunching the Finder has no effect on the sidebar icons.

**Comment by herbs** [comment]
Howdy,

I was under the impression that colorfulsidebar was dead under Sierra.

Good Luck,
herbs

**Comment by w0lfschild** [comment]
It does work on all Sierra Verizon's including the 10.12.4 beta. My guess is that the plugin is not being loaded into the Finder for you. 
You might have success closing and reopening the Finder window after it had started.

**Comment by w0lfschild** [comment]
<img width="901" alt="screen shot 2017-01-26 at 7 02 11 pm" src="https://cloud.githubusercontent.com/assets/1920148/22359211/fd26591c-e3f9-11e6-8b70-81f69eb09e68.png">
