### ISSUE TITLE
Some SIMBL preferences not saved

### ISSUE THREAD

**Issue by herbs** [w0lfschild/mySIMBL#24]
Howdy,

In mySIMBL 0.5.1, under the SIMBL tab, the two check boxes `Allow load in Xcode 8+' and Allow load in Safari Tech Preview' do not retain their manually unchecked value between runs of mySIMBL. Not a big deal.

Good Luck,
herbs

**Comment by w0lfschild** [comment]
Currently they're broken. Will be fixed in the next release. Thanks for the feedback.

**Comment by w0lfschild** [comment]
Should be fixed in 0.5.3
