### ISSUE TITLE
mySIMBL update procedure

### ISSUE THREAD

**Issue by Fofer** [w0lfschild/mySIMBL#26]
Is it normal that every time the mySIMBL application updates itself and relaunches, I get an error that reports that SIMBL is not installed?  Then I have to click to (re) install SIMBL, and reboot, in order for mySIMBL to launch properly, without that error. 

Seems a bit odd to me, since I'd properly installed SIMBL previously (disabling SIP and re-enabling SIP afterward.)  And it's the mySIMBL app, not SIMBL that's updating, anyway.

Everything works fine, I'm just wondering...

**Comment by w0lfschild** [comment]
That's definitely not how it's supposed to work. Sounds like you might be having an issue with the SIMBLAgent failing to update.
