### ISSUE TITLE
SIMBL  version 0.5.3 (29)

### ISSUE THREAD

**Issue by Chris222b** [w0lfschild/mySIMBL#27]
Bug with JAVA  ( jre-8u121-macosx-x64.dmg )  ,  when SIMBL is active : **JAVA** 8 / 121 is **blocked**

**Comment by w0lfschild** [comment]
I don't have java installed so I'm not quite sure what this means?

**Comment by Chris222b** [comment]
On Sierra 10.12.2  , (using JAVA with graphics), when SIMBL is activated, JAVA does not start, it seems to be blocked ... as soon as I disable SIMBL, JAVA is activated again.

**Comment by w0lfschild** [comment]
Does it still crash if you just disable SIMBL for JAVA using the blacklist?

**Comment by Chris222b** [comment]
After TEST, I use ProRealTime chart, and also, checked JAVA detection on the Oracle page: on / of

If SIMBL 0.5.3 is enabled, without Afloat 2.5.2, nor winBuddy 0.2.7, so without any extension: JAVA starts: OK!

If I only activate Afloat: JAVA does not launch

If I only activate winBuddy: JAVA does not launch

Also, the following message in system preferences: An error occurred in the Security and privacy preferences.
No access to security preferences!

Everything turns normal when I disable Afloat or winBuddy.

thank you for your work

**Comment by w0lfschild** [comment]
Probably has to do with those plugins trying to edit the application menus which I have seen reported as causing some crashes before. Not sure why that is though, and I don't use JAVA to test this out.
