### ISSUE TITLE
SIMBL install not working?

### ISSUE THREAD

**Issue by ylluminate** [w0lfschild/mySIMBL#3]
Just downloaded mySIMBL and found that using the `Install` function right off the bat to get SIMBL installed is not actually installing SIMBL or giving any feedback.  Any thoughts?  Haven't looked into logs yet, but wanted to throw this out there for some thoughts before digging.

**Comment by w0lfschild** [comment]
No I don't really know why it wouldn't work as long as System Integrity Protection is disabled.

**Comment by w0lfschild** [comment]
Is this working in recent versions?

Logging for SIMBL install/update is located @ `~/Library/Application Support/mySIMBL/logs`
