### ISSUE TITLE
mySIMBL doesn't appear to able to inject in 10.12.4 Beta (16E183b)

### ISSUE THREAD

**Issue by saagarjha** [w0lfschild/mySIMBL#30]
It's me again with issues getting mySIMBL to load in the latest developer beta. Would you mind taking a look at it?

**Comment by w0lfschild** [comment]
I'm not having this issue. Is the SIMBLAgent running?

**Comment by saagarjha** [comment]
Hmm…it only appears to start every *second* launch of mySIMBL.app. Is this the intended behavior? 

Anyways, the injection appears to work find when mySIMBLAgent is running (except for binventory, which I guess was broken in this beta).

**Comment by saagarjha** [comment]
Well, the plugins appear to work now, but I'm still having issues with "Xcode 8+" and Safari Technology Preview. I'm getting

```
Error loading /System/Library/ScriptingAdditions/SIMBL.osax/Contents/MacOS/SIMBL:  dlopen(/System/Library/ScriptingAdditions/SIMBL.osax/Contents/MacOS/SIMBL, 262): no suitable image found.  Did find:
	/System/Library/ScriptingAdditions/SIMBL.osax/Contents/MacOS/SIMBL: mach-o, but wrong architecture
	/System/Library/ScriptingAdditions/SIMBL.osax/Contents/MacOS/SIMBL: mach-o, but wrong architecture
```

in the Console every time I try to inject into them.

**Comment by siddharthalodha** [comment]
Yeah. Safari stand is not working for me too. Other plugins are working fine.

**Comment by bogdangit80** [comment]
cosyTabs 1.4.4 is not working in MacOS 10.12.4 with mySIMBL 0.5.3 (29)

**Comment by w0lfschild** [comment]
This is an issue with Apple implementing Library-Validation.

See my post here for more info: https://github.com/anakinsk/SafariStand/issues/38#issuecomment-289665394

**Comment by w0lfschild** [comment]
Check out the AMFI toggle in 0.7.0 if you want to load plugins into some of Apples protected applications.
