### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by thiagoveloso** [w0lfschild/mySIMBL#31]
Thanks for this awesome app! I was just wondering when the mySIMBL app is going to receive a new, more pleasant icon. It really deserves it!

**Comment by w0lfschild** [comment]
When someone else contributes an icon. I'm not artist so the current one is about as good as I'm gonna get it but I'll gladly take pull requests for icon art and UI design stuff (assuming they're not horrendous).

**Comment by eklecticgeek** [comment]
I can make an icon, give me some ideas

**Comment by thiagoveloso** [comment]
Cool, thanks for willing to contribute. I have two ideas, though I'm not sure Wolfgang would agree with them:

1) SIMBL can be used in a multitude of applications, and SIMBL is also a plugin manager. Therefore, SIMBL is multipurpose. Therefore, perhaps the icon could be a fancy toolbox with the letters 'SIMBL' on it?

2) SIMBL is famous for supporting the Afloat plugin, whose purpose is to keep applications afloat, or 'hang them to a wall' - the computer screen. Therefore, perhaps the icon could be a hammer with a nail hanging a frame to a wall? Something like this: https://thumb7.shutterstock.com/display_pic_with_logo/1014845/135470879/stock-vector-orange-sign-with-a-rope-hanging-from-a-nail-135470879.jpg, but adding a fancy hammer hitting the nail and with the letters 'SIMBL' inside the picture...

Again, not sure if Wolfgang would approve any of those ideas...

**Comment by eklecticgeek** [comment]
Hello Thiago, yesterday I catched Wolfgang on gitter for a couple of minutes and we were talking about an icon relating to "lego" blocks or similar building toys, in part for the idea of "building something plugging something on something else", in part because apple is already using the building block for bundles, and that's the icon for simbl bundles.. so I was oriented to a building blocks box or similar, but.. let's see

**Comment by thiagoveloso** [comment]
@eklecticgeek no problem man, as I said before I just threw out the first ideas that came out of my mind, recognizing that they might very well not be the best ones. And no one better to suggest the icon than the developer himself, right? ;) Looking forward to seeing how the final result will turn out...
