### ISSUE TITLE
SIP status isn't being properly returned.

### ISSUE THREAD

**Issue by Shugabuga** [w0lfschild/mySIMBL#32]
I have rootless/SIP disabled and despite that, SIMBL says I still need to disable SIP.

![screen shot 2017-03-11 at 10 20 06 pm](https://cloud.githubusercontent.com/assets/10801851/23828729/f14e8430-06a8-11e7-8b30-4ef2e7e1973d.png)

**Comment by w0lfschild** [comment]
No that's actually correct.
```
Green = SIP on
Red   = SIP off
```

**Comment by Shugabuga** [comment]
Oh. Closing this then.
