### ISSUE TITLE
mySIMBL agent is not loading plugins into all applications

### ISSUE THREAD

**Issue by Shugabuga** [w0lfschild/mySIMBL#33]
So the mySIMBLAgent is being started when I log in, but it is not injecting my plugins. I am on macOS 10.12.2 (16C67) with mySIMBL 0.5.3 (29). I:

1) Tried rebooting by machine to ensure it was being loaded on log-on

2) Tried re-opening mySIMBL a couple of times.

3) Disabled SIP.

The plugins only work if the `Load into all applications` button is pressed after a reboot.

Images:

<img width="311" alt="It is being loaded at log-on" src="https://cloud.githubusercontent.com/assets/10801851/23828848/045698d4-06ad-11e7-9dd8-bf1367ace946.png">

![Version info](https://cloud.githubusercontent.com/assets/10801851/23828860/6f560976-06ad-11e7-865e-4e88b47309b0.png)

Thank you for any help or insight you can provide, as well for maintaining everything you made!

**Comment by w0lfschild** [comment]
mySIMBLAgent just looks for updates for mySIMBL and that's about it.

`/Library/Application\ Support/SIMBL/SIMBLAgent.app` is what does the injecting of plugins, so you should make sure that's running.

It's run as a LaunchAgent `/Library/LaunchAgents/net.culater.SIMBL.Agent.plist`.

**Comment by Shugabuga** [comment]
Just added that to open on login manually and it works beautifully. Thanks!
