### ISSUE TITLE
Uninstall SIMBL

### ISSUE THREAD

**Issue by shcaerp** [w0lfschild/mySIMBL#35]
I cannot uninstall SIMBL on Sierra 12.4.  I have clicked the uninstall - logged out and back in - and the agent is still installed and running as well as the osax.  Is there another way?

**Comment by w0lfschild** [comment]
You can always manually delete the files. Check out this file for a full idea of what's removed.

`/Applications/mySIMBL.app/Contents/Frameworks/SIMBLManager.framework/Versions/A/Resources/removeSIMBL`

**Comment by PhilipTrauner** [comment]
Issue still seems to persist. I was unable to uninstall by clicking the uninstall button in mySIMBL, executing the uninstall binary worked fine, though.

**Comment by nickatsegment** [comment]
The uninstall script has a bug in it:

```
+ echo 'Removing files'
Removing files
+ for i in '"${cleanupFiles[@]}"'
+ echo Removing: '/Library/Application Support/SIMBL'
Removing: /Library/Application Support/SIMBL
+ nukeFiles '/Library/Application Support/SIMBL'
+ [[ -e /Library/Application Support/SIMBL ]]
+ [[ -f /Library/Application Support/SIMBL ]]
+ rm -vr '/Library/Application Support/SIMBL'
override rw-r--r--  root/admin for /Library/Application Support/SIMBL/SIMBLAgent.app/Contents/_CodeSignature/CodeResources?
```
Should be `rm -rvf` probably

**Comment by olets** [comment]
Didn't think to notice where these lived, but I trashed `/Applications/mySIMBL.app` rather than `rm`ing it and AppTrap found these additional deletable things:

- a directory org.w0lf.mySIMBL/
- a directory org.w0lf.mySIMBLHelper/
- a file org.w0lf.mySIMBL.plist
- a file org.w0lf.mySIMBLHelper.plist

**Comment by Dragvice** [comment]
Is there a fail safe way to uninstall mysimbl because i was getting mysimbl asking for permission ever since i upgraded to macOS Mojave and i had moved mysimbl to trash before upgrading to mojave and in mojave i installed mysimbl again

Plus: sorry for being late to the conversation

**Comment by olets** [comment]
Don't know but (per the README) mySIMBL is deprecated and replaced by https://github.com/MacEnhance/MacForge. Probably best to use that instead

**Comment by Dragvice** [comment]
thx ill give it a try

**Comment by albertputinjobs** [comment]
try these commands to completely remove it launchctl list | egrep {SIMBLAgent} and launchctl remove {SIMBLAgent}
