### ISSUE TITLE
SIP Disabled..mySIMBL disagrees..

### ISSUE THREAD

**Issue by drewauff** [w0lfschild/mySIMBL#36]
SIMBL page, SIP notified as enabled when it is disabled.

**Comment by w0lfschild** [comment]
Is the dot red or green?

Green = on
Red = off

I understand it does seem counter intuitive where someone might think green as being off which would allow for SIMBL to install it's injector.

**Comment by drewauff** [comment]
ahh, my mistake then. Yes it is counter intuitive..

I thought it was playing up with new MacOS update.

Thanks for the prompt reply 👍
