### ISSUE TITLE
Afloat install issue

### ISSUE THREAD

**Issue by mgiddings10** [w0lfschild/mySIMBL#37]
Hi trying to install always on top and getting this error message: 
<img width="1006" alt="screen shot 2017-03-28 at 3 21 09 pm" src="https://cloud.githubusercontent.com/assets/26749501/24423369/b8e49fb0-13ca-11e7-8aac-d3ed318767bc.png">

**Comment by w0lfschild** [comment]
Do you have System Integrity Protection off? Look in the SIMBL tab a red dot is off and a green dot is on.

If it's not off you need to follow that guide you're reading in the background:

> In some instances the installation might not be able to be carried out due to Mac’s System Integrity Protection. You will have to disable System Integrity Protection before you can run the installation.
>
> To disable System Integrity Protection:
>
* Reboot your Mac. When the startup screen shows up, press and hold the “Command + R” keys until the Apple logo appears on your screen.
* Once it finishes loading and brings you to Recovery Mode, click “Utilities -> Terminal.”
* In the Terminal window type in csrutil disable and press Enter.
* Restart your Mac.
> Note: to re-enable System Integrity Protection, repeat the above steps but change the command to csrutil enable. It is recommended to re-enable System Integrity Protection after installing mySIMBL.

**Comment by mgiddings10** [comment]
Thanks for emailing. I did turn off, then got that message. Then went to reenable and now it will turn on but not boot. 
The hard drive became unmounted. I have firmware password does that impact it?


Please excuse typos- on the go! 
(202) 569-2818

**Comment by mgiddings10** [comment]
Have macbook pro running Sierra (I think it's sierra) using chrome
Have firmware password
Not sure if I had on filevault- I'm 90% sure I had turned it off a few months ago 

I downloaded the SIMBL app, tried to install but ran into error message about SIP on. 
Followed instructions to diable SIP.
rebooted normally, everything worked fine. 
Went to reinstall SIMBL and got a new error message. Screenshot of that error sent to you earlier
​
 b8e49fb0-13ca-11e7-8aac-d3ed318767bc.png​
Downloaded Afloat bundle and tried to drag and drop correct bundle file to SMIBL to see if I could get it to run anyways. 
Didn't work- nothing seemed to happen.
Decided oh well and to look at it later. 
Went to renable SIP in recovery mode as recommended and upon restart after entering in enable command it only gets halfway through bootup- makes sound, apple appears and progress bar gets halfway through
Then black screen

Will enter into recovery mode but will not do diagnostic or single user mode
Harddrive was not mounted when going in for disk utility, had to force mount. 
Found harddrive on Disk 2

Hard drive recognized now but will not let reinstall OS in recovery mode. Error message when downloading Sierra in recovery mode. 
Disk utility first aid still stops at filesytem error. 
Apple in-store diagnostic states HFC+ systemfile error integrity check but for DISK ONE
Won't recogonize netboot commands in termnial

**Comment by w0lfschild** [comment]
Honestly sounds like an issue unrelated to mySIMBL that just happened to occur around the same time. It's quite possible your harddrive is failing.

If you can mount your harddrive in recovery mode you might look at the log file for the installation at:

`/Volumes/<harddrive>/Users/<username>/Library/"Application Support"/mySIMBL/logs`

The installation script is quite simple, here's the entire script:

``` bash

#!/bin/sh

# Update SIMBL and remove possible old or alternate version

function nukeFiles() {
    if [[ -e "$1" ]]; then
        if [[ -f "$1" ]]; then
            rm -v "$1"
        else
            rm -vr "$1"
        fi
    fi
}

function createFolder() {
	if [[ ! -e "$1" ]]; then
        mkdir -pv "$1"
	fi
    chmod 777 "$1"
}

log_dir="$HOME"/Library/"Application Support"/mySIMBL/logs
createFolder "$log_dir"
exec &>"$log_dir"/installSIMBL.log
 
cleanupFiles=(
	"/Library/Application Support/SIMBL/SIMBLAgent.app"
	"/Library/LaunchAgents/net.culater.SIMBL.Agent.plist"
	"/System/Library/LaunchAgents/net.culater.SIMBL.Agent.plist"
    "/Library/ScriptingAdditions/SIMBL.osax"
    "/Library/ScriptingAdditions/EasySIMBL.osax"
    "$HOME/Library/Application Support/SIMBL"
    "$HOME/Library/ScriptingAdditions/SIMBL.osax"
    "$HOME/Library/ScriptingAdditions/EasySIMBL.osax"
    "/System/Library/ScriptingAdditions/SIMBL.osax"
    )

setupFolders=(
	"/Library/Application Support/SIMBL/Plugins"
	"/Library/Application Support/SIMBL/Plugins (Disabled)"
	"/Library/Application Support/SIMBL"
	)

launchctl unload /Library/LaunchAgents/net.culater.SIMBL.Agent.plist
killall SIMBLAgent

echo "Removing old files"

for i in "${cleanupFiles[@]}"; do
    echo Removing: "$i"
    nukeFiles "$i"
done

echo "Setting up folders"

for i in "${setupFolders[@]}"; do
    echo Setting up: "$i"
    createFolder "$i"
done

echo "Installing SIMBLAgent"

mySIMBL=$(dirname "$0")
cp -vr "$mySIMBL"/SIMBL.osax /System/Library/ScriptingAdditions/
cp -vr "$mySIMBL"/SIMBLAgent.app "/Library/Application Support/SIMBL/"
cp -v "$mySIMBL"/SIMBLAgent.app/Contents/Resources/net.culater.SIMBL.Agent.plist "/Library/LaunchAgents"

echo "Launching Agent"

launchctl load /Library/LaunchAgents/net.culater.SIMBL.Agent.plist

echo "Done"


```
