### ISSUE TITLE
Plugins prevent Terminal from opening first window macOS 10.12

### ISSUE THREAD

**Issue by aneilbaboo** [w0lfschild/mySIMBL#38]
Steps to reproduce:

System: macOS Sierra 10.12.4
mySIMBL: 0.5.3 (29)
Afloat: 2.5.2 / Jan 18, 2017

1. Install and run mySIMBL
2. Select Afloat plugin from Discover tab and install
3. Try opening Terminal (click Dock icon)
   Terminal app starts but no terminal window appears
4. Try opening Terminal again
   A terminal window appears

Note, that if you've defined a default window group it does not open on step 3 or 4.  Only a single window appears on step 4.

**Comment by w0lfschild** [comment]
I think simply being injecting into causes Terminal to have this issue, not Afloat specifically.

**Comment by w0lfschild** [comment]
I think this is no longer an issue in 10.13 so I'm probably not gonna look into this.
