### ISSUE TITLE
Library-Validation issues

### ISSUE THREAD

**Issue by w0lfschild** [w0lfschild/mySIMBL#39]
mySIMBL does not inject into applications with Library-Validation which currently includes:

Safari 10.1 +
Xcode 8.0 +

Not sure if/when a fix will come. You can unsign these applications to allow injection but Safari is protected by System Integrity Protection which mean SIP must be off in order to unsign Safari. There are also a host of issues that have been reported related to unsigning Safari 10.1.

-Wolf :wolf:

**Comment by ZimM-LostPolygon** [comment]
Can you provide a link on how to unsign an application?

**Comment by w0lfschild** [comment]
Library Validation is separate from SIP and is active even when SIP is disabled.

Here's the tool to unsign something https://github.com/steakknife/unsign

**Comment by w0lfschild** [comment]
0.7.0 lets you turn off AMFI which should fix this issue.
