### ISSUE TITLE
Where's the download?

### ISSUE THREAD

**Issue by mrdanimal** [w0lfschild/mySIMBL#4]
The README says to download the latest release, but doesn't provide a link. Is there a download that you know hasn't been bundled with adware? I'd rather not install from a random site found on google. Thanks!

**Comment by inket** [comment]
The releases page is here: https://github.com/w0lfschild/mySIMBL/releases

**Comment by Ritchie007** [comment]
How about a 0.2.5 compiled release, please.

**Comment by fnankivell** [comment]
Can't you get the update through the app itself? I updated to 0.2.5 just fine this morning...

**Comment by mrdanimal** [comment]
Thanks. When I downloaded the one from the releases page, it updated.
