### ISSUE TITLE
Microsoft Word 2016 Glitch

### ISSUE THREAD

**Issue by macboeuf** [w0lfschild/mySIMBL#41]
Hi,

Have there been any known issues with bundles and Word 2016? Ever since I set up SIMBL and all the rest, I haven't been able to save a document -- either it won't let me click, or the save dialog opens and closes in immediate succession. I've tried removing all bundles, reinstalling them, turning off window-related features, but to no avail. Any help would be appreciated.

**Comment by w0lfschild** [comment]
Most likely a bug with a specific plugin like aFloat or winBuddy.

You could disable loading of plugins into Word in the SIMBL tab of mySIMBL.

**Comment by macboeuf** [comment]
Thanks for the assistance. Seems to have been winBuddy -- disabling the latter fixed it. Cheers!
