### ISSUE TITLE
Plugin update fails

### ISSUE THREAD

**Issue by youngcadam** [w0lfschild/mySIMBL#45]
I tried "Update All" as well and nothing happened. I was then greeted with this error
<img width="696" alt="imgurlwindow 09-06-17 19_06_50" src="https://user-images.githubusercontent.com/17751995/26999104-dc799b46-4d46-11e7-8f5c-8117ce23c16f.png">

**Comment by w0lfschild** [comment]
For now you can manually download and install it here : https://github.com/w0lfschild/myRepo/raw/master/mytweaks/bundles/Afloat_2.5.2.zip
