### ISSUE TITLE
Is disabling System Integrity Protection required?

### ISSUE THREAD

**Issue by xavierartot** [w0lfschild/mySIMBL#46]
I don't feel save without:  System Integrity Protection
As developer I installed many dependencies and the risk extist.
You don't have another way to install mySimbl without disable SIP?

**Comment by w0lfschild** [comment]
Unfortunately mySIMBL needs to install files in places protected by SIP in order to function.

SIP can be re-enabled after the initial SIMBL install though.

**Comment by xavierartot** [comment]
How I re-enabled after the initial SIMBL install?
Thanks

**Comment by w0lfschild** [comment]
The process to re-enable is the same as disabling except that the command used to re-enable is

`csrutil enable`

**Comment by NanoDrivee** [comment]
I've tried running this command after installing mySIMBL and it seems to work successfully (I wait 10 seconds before rebooting and type `csrutil status` but it doesn't seem to work, not sure if this is intended behaviour?) When I reboot into macOS and type `csrutil status` it says that SIP is disabled still. Any suggestions?
