### ISSUE TITLE
System framework hooking

### ISSUE THREAD

**Issue by suclogger** [w0lfschild/mySIMBL#48]
Hi:
    I was playing with IAP on OSX 10.12.5 and tried to hook into `StoreKit` to bypass purchase check.
    But I found it unable to hook into it.My project is in [here:](https://github.com/suclogger/ipichack)
    Would you please help me with this issue?
    Thanks very much!

**Comment by w0lfschild** [comment]
Does it work if you hook an application using that framework?

Right now mySIMBL is not quite like Cydia Substrate. It doesn't hook frameworks.
