### ISSUE TITLE
Text cut off in Discover descriptions

### ISSUE THREAD

**Issue by EnricoMonese** [w0lfschild/mySIMBL#50]
Description text in the Discover tab gets cut off.

Using _macOS 10.13 High Sierra Beta_

![schermata 2017-07-08 alle 14 47 58](https://user-images.githubusercontent.com/19847464/27985524-8f138cc4-63ec-11e7-9cc9-21b96f529f9c.png)

**Comment by w0lfschild** [comment]
Yeah the area below is supposed to be for like pictures and the description is supposed to be scrollable.

Thanks for pointing that out. Probably need to figure out a better layout for the bundle page.

**Comment by w0lfschild** [comment]
Fixed in 0.7.0
