### ISSUE TITLE
MySIMBL install on Sierra  - Mail Glitch

### ISSUE THREAD

**Issue by lpeckmtb** [w0lfschild/mySIMBL#51]
I installed MySIMBL and while it works, now my Apple Mail is failing to open file/save file.  I went through this once before, and the issue was the MySIMBL - I reinstalled it today hoping the bug was fixed, but no luck - back to same issues.

<img width="479" alt="screen shot 2017-07-10 at 12 56 26 pm" src="https://user-images.githubusercontent.com/30057587/28037912-e86688a4-6571-11e7-95bd-62cab58d58e1.png">

**Comment by w0lfschild** [comment]
Hmm. It's probably due to a specific plugin but I don't know what. Does this happen with no plugins enabled? Maybe just blacklist Mail in the SIMBL tab.
