### ISSUE TITLE
simbl install failed!

### ISSUE THREAD

**Issue by veevalkonen** [w0lfschild/mySIMBL#53]
First popup when starting SIMBL: 
SIMBL Manager has determined that SIMBL is not installed or outdated on your system.

SIMBL is latest version as is OS X.
Trying to d&d afloat to the simbl (there's no plugins section visible) and it gives me error message:
simbl install failed!

**Comment by w0lfschild** [comment]
What version of the osax is installed?

The SIMBL tab should look like this:

<img width="842" alt="screen shot 2017-07-18 at 2 20 04 pm" src="https://user-images.githubusercontent.com/1920148/28340735-a1ec50f2-6bc5-11e7-8466-8036bff4ca68.png">

You probably just need to disable System Integrity Protection to update the osax.

**Comment by vesputs** [comment]
Hi,

10.12.5

Best,
Vesa

**Comment by npyl** [comment]
he asked for the version of SIMBL.osax

**Comment by vesputs** [comment]
Thanks, just edited it:

EDIT: mySIMBL version 0.5.3 (29)

**Comment by w0lfschild** [comment]
That's the app version not the version of the simbl.osax you have installed.

Once again I will state that you probably just need to disable System Integrity Protection to update the osax.

**Comment by qwertimus** [comment]
Sorry to necro this thread...
@vesputs Which version of Mac are you running? I've just installed 10.13b9 on a system and encountered the same issue you've described, although no error message.
To resolve the issue, I had to manually copy the file (SIMBL.osax) to its correct location. SIP is disabled, and 'Allow apps' was forced to 'Everywhere' for testing.

**Comment by vesputs** [comment]
Uninstalled the app.

**Comment by qwertimus** [comment]
@vesputs Regardless, do you remember if you were on a High Sierra beta?

**Comment by vesputs** [comment]
Nope, Sierra only.

**Comment by qwertimus** [comment]
@vesputs Okay, thank you for replying.
