### ISSUE TITLE
System Notifications Blocking Clicks

### ISSUE THREAD

**Issue by mkormendy** [w0lfschild/mySIMBL#54]
When a notification appears in the top right corner, I am unable to click anything directly below the notification all the way down to the bottom of the screen on the right-hand side of the screen. The width of this transparent layer is the entire notification wide.

When I dismiss the notification (eg. swiping it right) then any elements under the screen are clickable again.

This does not happen on my other system where mySIMBL is not installed.
Possible bug?

**Comment by w0lfschild** [comment]
It's surely a plugin and not mySIMBL itself. What plugins do you have installed?

**Comment by mkormendy** [comment]
I only have fullscreenER installed.

**Comment by w0lfschild** [comment]
Hmm I can't reproduce this. Does the issue persist if you disable fullscreenER and log out and back in?

**Comment by mkormendy** [comment]
Aha! .. So when I stopped fullscreenER, log out and back in .. there's no more click blocking.

**fullscreenER OFF**
![jul-19-2017 08-52-15](https://user-images.githubusercontent.com/1437667/28370574-36491ad8-6c60-11e7-987d-fabe26e05f6c.gif)

**fullscreenER ON**
![jul-19-2017 08-56-10](https://user-images.githubusercontent.com/1437667/28370601-4bb01264-6c60-11e7-8acf-485641cb6df7.gif)

**Comment by w0lfschild** [comment]
I just updated the plugin to blacklist NotificationCenter. Try updating in mySIMBL and logging out and back in to apply the change. 

Hopefully that works.

**Comment by mkormendy** [comment]
Yes that has fixed the clicked issue, as well it also fixed an issue with a ghosting layer on incoming facetime notifications where I couldn't click the answer button and had to swipe the layer away before answering the call. Cheers!

**Comment by mkormendy** [comment]
PS did you get my direct email to you about the idea of hover hiding windows?
