### ISSUE TITLE
darkNC doesn't work

### ISSUE THREAD

**Issue by gian8989** [w0lfschild/mySIMBL#55]
First thing: God bless you for this app!!

I can't make this work. It is always light theme; the only thing that change is the text that become even lighter.

All other plugins works without a problem.

**Comment by w0lfschild** [comment]
What version of macOS?

Do you have `Use dark menu bar and dock` checked in System Preferences > General?

**Comment by gian8989** [comment]
I am using macos 10.12.6.
I have followed all procedure:
- run the command `killall NotificationCenter`
- check `Use dark menu bar` and Dock in the `preferences.app`

The only difference is that text in notification center is white but the color of the panel is always light grey.

**Comment by w0lfschild** [comment]
Okay I'll have a look into this when I have time.

**Comment by gian8989** [comment]
ty

**Comment by gian8989** [comment]
I downloaded the update of DarkNC and It works but the text looks a bit pixellated. 
The thing is that i activate the option reduce transparency and the plugin doesn't work with it.
I am not sure but it was probably working right even before but forgot about the reduce transparency option activated.
