### ISSUE TITLE
Plugin ideas

### ISSUE THREAD

**Issue by ylluminate** [w0lfschild/mySIMBL#57]
Any place to stick ideas for plugins?  

For example, I've been so frustrated with Apple for the last few years for not implementing a "Reveal in Finder" and a drag-and-drop-to-Terminal-to-get-path functionality for Photos and they still haven't implemented it in 10.13!  

Very upsetting and I got to thinking that it might be a good idea to have a list that folks could contribute to for ideas of things that are needed in the way of SIMBL plugins.

**Comment by gian8989** [comment]
I don't understand where you need "Reveal in Finder" but if you need path you can solve it with TotalFinder ([link](https://totalfinder.binaryage.com/menus))

**Comment by w0lfschild** [comment]
Unfortunately Photos is protected by library-validation which is still something that I don't really have a way around other than stripping code signing which generally messes up the app and requires SIP to be off since Apple Apps are protected by SIP now.

**Comment by w0lfschild** [comment]
Well with the latest version of mySIMBL you can load plugins into Photos if you turn off AMFI and SIP.

Maybe someone could make this now.
