### ISSUE TITLE
Multiple Users SIMBL hang

### ISSUE THREAD

**Issue by minimum91** [w0lfschild/mySIMBL#59]
Have you tried using SIMBL with multiple users set up?
I haven't up until now. I created an additional account for my girlfriend (non admin, obviously) and tried to log in. On first glance everything works fine, but after multiple tests and switching users, it seems like SIMBL completely hangs any application that it touches on that other account. As soon as I blacklist any app - it runs fine. Meanwhile, on my my Admin account, everything is fine and dandy.
I tried Installing mySIMBL to my home directory, so that it doesn't affect the other account, but it does not work that way. 

macOS Sierra 10.12.6

**Comment by w0lfschild** [comment]
Interesting I haven't really tested multi-users. Could be a specific tweak maybe.

I'll try to look into it.
