### ISSUE TITLE
colorfulSidebar9 inject into other apps

### ISSUE THREAD

**Issue by Hari2139** [w0lfschild/mySIMBL#60]
Hi,

I have installed mySIMBL version 0.5.3. The colorfulSidebar9 works perfectly in the Finder app, but does not get injected into other apps like Safari browser (File > Save As...). Does the plugin support this feature?

![image](https://user-images.githubusercontent.com/4117255/29976802-2c7cef5e-8ef0-11e7-94da-2a628b3439b7.png)

Thanks,
Hari

**Comment by w0lfschild** [comment]
Added with colorfulsidebar_9 1.5.0

Still probably won't load in Safari though because of Library Validation : https://github.com/anakinsk/SafariStand/issues/38

**Comment by Hari2139** [comment]
Thank you w0lfschild!
