### ISSUE TITLE
Can't install on macOS 10.12.6

### ISSUE THREAD

**Issue by zhongqin0820** [w0lfschild/mySIMBL#62]
![crash info](http://ovnuv29fq.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-10-04%2001.02.09.png)

**Comment by gian8989** [comment]
Disable Integrity Protection:
	1.	Reboot your Mac into Recovery Mode by restarting your computer and holding down Command+R until the Apple logo appears on your screen.
	2.	Click Utilities > Terminal.
	3.	In the Terminal window, type in csrutil disable and press Enter.
	4.	Restart your Mac.

**Comment by w0lfschild** [comment]
Yup what @gian8989 said.

It's supposed to show a warning saying you need to do that when you first start the app if it's not already been done. Maybe there's an issue with that not showing in some cases.

Might need to make it so you can't dismiss the warning without quitting the app.
