### ISSUE TITLE
Afloat and SizeWell Window Plugins Not Working On 10.13

### ISSUE THREAD

**Issue by GodBlesses** [w0lfschild/mySIMBL#63]
Both Afloat and SizeWell don't work on my config of macOS 10.13 (High Sierra).  I don't know if mySIMBL needs an update to correct this issue or if the plugins themselves need bug fixing.  The versions I am using are mySIMBL 0.5.3 (29), Afloat 2.5.2 and SizeWell 0.8.2. All of these are the latest versions that I found.  As a side note, I am using other mySIMBL plugins that work fine on my machine.

**Comment by w0lfschild** [comment]
Afloat is working for me on 10.13.2 ?

Not sure about what SizeWell is but I'd guess it's broken and since I don't maintain it I can't help with that one.

**Comment by minimum91** [comment]
SizeWell has long been discontinued. MenuAndDockless replicates some if not most of what sizewell did.
