### ISSUE TITLE
mySIMBL is a folder not an executable file?

### ISSUE THREAD

**Issue by rasikananda** [w0lfschild/mySIMBL#65]
I'm trying to install mySIMBL but your instructions say "- Open mySIMBL
    - mySIMBL will ask to be moved to /Applications" but the only thing that I have is the folder mySIMBL and there is nothing executable there.

What do I do? Please update your installation instructions for people like me.

**Comment by w0lfschild** [comment]
Did you download the project?

Get a release. https://github.com/w0lfschild/mySIMBL/releases/download/0.5.3/mySIMBL-29.zip
