### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by khrisanfov** [w0lfschild/mySIMBL#66]
Hello!
I am trying to build mySIMBL on MacOS Sierra.
I run this in terminal:

`xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"`

and got an error:

> ** BUILD FAILED **
> The following build commands failed:
> 	PBXCp build/Release/mySIMBLAgent.app build/Release/mySIMBL.app/Contents/Library/LoginItems/mySIMBLAgent.app
> (1 failure)

How to fix it?

**Comment by fnankivell** [comment]
Do you absolutely need to build it? Would a release version be easier?

https://github.com/w0lfschild/mySIMBL/releases

**Comment by khrisanfov** [comment]
@fnankivell I need 32bit or universal arch, release build is 64 only. It does not hook 32bit applications.

**Comment by w0lfschild** [comment]
Not sure I've never built via command line. Either way you want to be building the framework because that's what's gonna actually let you load into 32 bit apps. I think I tried to do this once but gave up as it wasn't really simple and 32 bit is basically dead. 

https://github.com/w0lfschild/mySIMBLFramework

**Comment by Violet-01** [comment]
@khrisanfov To do a command line build, `cd` into the git directory where you downloaded the project and into the mySIMBLFramework directory `SIMBL-Devel/mySIMBLFramework`

open the the SIMBL Frameworks.xcodeproj and select "automatically manage signing" for the targets **SIMBL FrameworksTests**, **SIMBLManager**, **SIMBLAgent**, and **SIMBL** 

_( you will need at least the free developer account associated with an AppleID. This can be created/ applied to your existing AppleID at Developer.Apple.com )_

In the terminal you would `set -o pipefail && xcodebuild -configuration Release`

After the SIMBL Frameworks project successfully builds, `cd` back to the root project directory and open the mySIMBL.xcodeproj. Similarly select "automatically manage signing" for the targets **mySIMBL**, **mySIMBLAgent**

In the terminal `set -o pipefail && xcodebuild -scheme 'mySIMBLAgent' -configuration Release`

After this completes successfully you would `set -o pipefail && xcodebuild -scheme 'mySIMBL' -configuration Release` and all should be well.

The issue I think is that the default configuration for command line builds is to only build the mySIMBL target which required the mySIMBLAgent target to already be built.
