### ISSUE TITLE
mySIMBL plugins only work with SIP disabled

### ISSUE THREAD

**Issue by samaero** [w0lfschild/mySIMBL#67]
Edit: this issue was my own user error and can be closed (sorry!). FWIW, I had written a script to delay loading the SIMBLAgent until some other startup processes were complete, as loading it earlier conflicted with an input manager I use...when I upgraded to High Sierra, the script was removed from my startup items, so SIMBLAgent was not running.

**Comment by w0lfschild** [comment]
No problem. I'll close this.
