### ISSUE TITLE
Installation documentation is incomplete / incorrect

### ISSUE THREAD

**Issue by mattdarwin** [w0lfschild/mySIMBL#68]
In the Installation section of the documentation, it says:
- Download the [latest release](https://github.com/w0lfschild/app_updates/raw/master/mySIMBL/mySIMBL_master.zip)
- Unzip the download if your browser does not do so automatically
- Open mySIMBL
  - mySIMBL will ask to be moved to /Applications

Unfortunately "Open mySIMBL" is ambiguous.  After I have downloaded it, I just have a folder called "mySIMBL-master".  "Opening" this folder just involves viewing the contents of this folder in Finder - there is no way to actually start the application.

**Comment by w0lfschild** [comment]
I think maybe you're having some issue with the download?

The download is a .zip file called `mySIMBL_master.zip`

When you unzip`mySIMBL_master.zip` the only item inside is `mySIMBL.app`

**Comment by thecodercody** [comment]
Mattdarwin is correct.  There is only tons of folders and random files, but no mySIMBL.app.  For sure.

**Comment by thecodercody** [comment]
Check it out mattdarwin I found it.  https://github.com/w0lfschild/mySIMBL/releases/download/0.5.3/mySIMBL-29.zip

**Comment by w0lfschild** [comment]
I think both of you were for some reason downloading the whole project. I'm going to close this issue.
