### ISSUE TITLE
Safari plugins not working

### ISSUE THREAD

**Issue by EredLithui** [w0lfschild/mySIMBL#73]
Hey,

I hope the fault isn't on my side but I've tried everything I could think of and as it seems to be a problem with Safari I thought I'd finally try it here.
The problem is that SafariStand and cosyTabs won't work for me while plugins like cleanHud and spotifyPlus do. SIP is disabled and I'm running latest High Sierra+Safari 11 (reinstalled the last big update just to try).

Anybody with a similar problem and/or is there a known fix?

**Comment by w0lfschild** [comment]
SIP and AMFI must be disabled to load into some system applications like:

Safari
iTunes
Xcode

Version 0.7.0 has a toggle to disable AMFI
