### ISSUE TITLE
Improve first-run experience

### ISSUE THREAD

**Issue by ryandesign** [w0lfschild/mySIMBL#74]
When I run mySIMBL 0.5.3 for the first time, a dialog box is shown:

> SIMBL Manager has determined that SIMBL is not installed or outdated on your system.
> This means that applications and plugins which require SIMBL to function will likely not work.
> [Cancel] [Install]

For one thing, this window and the dialog box float atop all applications. This is not desired.

More importantly, the wording of the message is off-putting. A friendlier wording of this message might be:

> Welcome to mySIMBL! mySIMBL needs to install some components on your system in order for applications and plugins that use SIMBL to work.

If I click Install, an even unfriendlier message is displayed:

> SIMBL install failed!
> Something went wrong, probably System Integrity Protection.
> [Ok]

Certainly System Integrity Protection is enabled on my system, and I do not want to disable it permanently. mySIMBL should explain why it needs SIP to be off, that (according to #46) it can be reenabled after installation, and how to disable and reenable it.

Users don't like tunneling modal dialog box syndrome—one modal dialog box which leads to another. A better user experience would be to tell the user everything you need to tell them in a single dialog. If SIP is off, tell the user that immediately, and don't offer an Install button.

So, for example, if SIP is off, add a second paragraph to the welcome dialog such as:

> mySIMBL can't install these components now, because System Integrity Protection (SIP) is on. SIP needs to be disabled to install mySIMBL, but it can be reenabled after installation. Instructions for enabling and disabling SIP can be found here: [URL]

**Comment by w0lfschild** [comment]
I agree, thanks for the ideas.

**Comment by w0lfschild** [comment]
Done in 0.7.0
