### ISSUE TITLE
Every time I open the app it asks for an update

### ISSUE THREAD

**Issue by chloeeisoaky** [w0lfschild/mySIMBL#77]
eveyrtime I go on the app it asks for an update and it just keeps doing it and nothing works

**Comment by w0lfschild** [comment]
Maybe manually get the latest version? [Download](https://github.com/w0lfschild/app_updates/raw/master/mySIMBL/mySIMBL_0.7.0.zip)

**Comment by funemy** [comment]
Have the same problem here, manually replacing the old version with the newest release doesn't work.

**Comment by jatinkrmalik** [comment]
I have the same issue, also it doesn't seem to have any change in my UX because I think it's missing some components, hence the installation banner on start.

**Comment by thearkadia** [comment]
I get this issue still
