### ISSUE TITLE
Updating System Components Prompt

### ISSUE THREAD

**Issue by sammarcus** [w0lfschild/mySIMBL#82]
Hi!

Using version 0.7.1 on 10.13.4 and every time I open the application I am prompted to update system components:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/8689264/40500940-6bb132fe-5f54-11e8-846a-b9448aeac9ae.png">

I of course enter my password and do so, and it does not display any error, but this message is shown every single time I launch mySIMBL. It also does not appear that any of my plugins are working :(

This is same issue as the comment in https://github.com/w0lfschild/mySIMBL/issues/77#issuecomment-388901834 , cc @jatinkrmalik. The other issue seems to be concerned with updating the application version itself, not the components that are prompting. 

Is this related to simbl.osax showing as null?
<img width="408" alt="image" src="https://user-images.githubusercontent.com/8689264/40501079-d45d56b6-5f54-11e8-9f56-4e70167f984e.png">

**Comment by w0lfschild** [comment]
Yes most likely. It looks like you need to disable system integrity protection. That is required to install the osax. The real issue here is that it’s not telling you that for some reason.

**Comment by hexeric** [comment]
same problem, how to fix without disabling SIP?

**Comment by w0lfschild** [comment]
@hexeric mySIMBL requires that SIP be disabled to install the osax. If it's not installed then mySIMBL won't do anything.
