### ISSUE TITLE
After Recent Mac OS update 10.13.5 mySIMBLHelper won't run

### ISSUE THREAD

**Issue by born2fly** [w0lfschild/mySIMBL#84]
I just updated High Sierra to ver 10.13.5. Now I am getting an error message '**mySIMBLHelper cannot be opened because of a problem'**. My current version of mySIMBL is .0.7.1. Just trying to see if there is a fix for this condition.

**Comment by w0lfschild** [comment]
Is there any longer error message/log saved somewhere?

**Comment by born2fly** [comment]
Issue resolved.
