### ISSUE TITLE
MySIMBLHelper Problem Report Window will not close

### ISSUE THREAD

**Issue by born2fly** [w0lfschild/mySIMBL#85]
Recently updated High Sierra to 10.13.5 and now I have an error window that will not close. Problem didn't exist prior to update.

**Comment by w0lfschild** [comment]
Screenshot? What does the window say?

**Comment by born2fly** [comment]
Problem has been resolved by deleting all related mySIMBL files using Mac Remover. It was the only way I found that worked.
