### ISSUE TITLE
mySIMBL thinks sip in enabled when it is disabled

### ISSUE THREAD

**Issue by RogetK** [w0lfschild/mySIMBL#86]

**Comment by wwwonka** [comment]
same here, I'm on macOS Sierra 10.12.6.

**Comment by iliakan** [comment]
same here on Mojave. A checkbox means that it's enabled or not?

**Comment by waxfingers** [comment]
![mysimbl_sip_status_confussion_web](https://user-images.githubusercontent.com/13238340/48371288-68684b00-e6b3-11e8-823c-f5b659698b9b.jpg)

**Comment by iliakan** [comment]
right, that's what I see.
Now I enabled it, and there's no checkbox 8-O

**Comment by w0lfschild** [comment]
If you read the text below it says 
> Check represents disabled for SIP
