### ISSUE TITLE
"Insecure update error!" popup box from mysimblhelper and mysimbl

### ISSUE THREAD

**Issue by mclarence** [w0lfschild/mySIMBL#87]
I keep getting this popup box after updating to the latest version of high sierra (10.13.5). Clicking ok will just bring it up again after a few seconds
<img width="502" alt="screen shot 2018-06-18 at 8 29 42 pm" src="https://user-images.githubusercontent.com/25338414/41531351-622a7e66-7336-11e8-8c1f-62e834537e3f.png">
<img width="379" alt="screen shot 2018-06-18 at 8 31 07 pm" src="https://user-images.githubusercontent.com/25338414/41531398-8e5143b2-7336-11e8-8614-dacbe08be41f.png">

**Comment by w0lfschild** [comment]
Should be fixed now, thanks for the feedback.
