### ISSUE TITLE
Can't get anything to work

### ISSUE THREAD

**Issue by GijsMulders** [w0lfschild/mySIMBL#88]
I've tried several apps and none of them does anything.
(spaces-renamer, cDock, binventory)
The bundles do appear in the Plugins directory

Running MacOS 10.13.6, mySIMBL 0.7.1

Tried toggling AMFi but getting an error. 
<img width="729" alt="screen shot 2018-07-17 at 6 33 42 pm" src="https://user-images.githubusercontent.com/13457058/42851211-141eb512-89f1-11e8-84fd-3c6cd248da59.png">

**Comment by w0lfschild** [comment]
Looks like you don't have the SIMBL.osax installed so no plugins will ever work. 

It also looks like you have System Integrity Protection on. Not sure if the SIP warning video showed like it's supposed to but you can't really do anything without turning it off at least once.

Not sure why the AMFI toggle is failing, I can't remember if SIP needs to be off to toggle it or not but the only other thing I can think of is that you aren't entering the correct credentials. Turning it off is just adding `amfi_get_out_of_my_way=1` to the nvram boot-args.

Lastly cDock and spaces-renamer use applications to control their bundles so they won't really do anything if you just install them straight from mySIMBL.

You can try manually installing the .osax at `/System/Library/ScriptingAdditions`

**Comment by GijsMulders** [comment]
Thanks for the response!

I tried with SIP turned off but that gave me another strange error when toggling the AMFI.

I reinstalled with SIP turned off, and now all 4 textboxes are greyed out and the plugin is working. So not sure what went wrong but installing with SIP turned off seems to have done the trick.
