### ISSUE TITLE
mySIMBL is really slow and unresponsive

### ISSUE THREAD

**Issue by Patrik-svobodik** [w0lfschild/mySIMBL#89]
the app is really slow and doing anything takes too long for my taste

**Comment by w0lfschild** [comment]
If you're on Mojave they made some change to iconservices and the method for getting bundle icons massively spikes the CPU. It's fixed in MacPlus and if that's not out by the time Mojave rolls out publicly I'll push a fix for mySIMBL, it's possible I'll do that regardless.
