### ISSUE TITLE
mySIMBL showing incorrect SIP status in GUI

### ISSUE THREAD

**Issue by cmdshft** [w0lfschild/mySIMBL#90]
csrutil reports that SIP is disabled but mySIMBL is showing it still checked in the GUI.

![screen shot 2018-07-30 at 7 21 19 pm](https://user-images.githubusercontent.com/8571823/43428747-dcd159c4-942d-11e8-8e5b-abd1bd78454d.png)

**Comment by w0lfschild** [comment]
Did you read the text below it?

"Check represents disabled for SIP"
