### ISSUE TITLE
Conflict between colorfulSidebar9.bundle and Canon camera software

### ISSUE THREAD

**Issue by alwaysannoyed** [w0lfschild/mySIMBL#93]
The Canon software for downloading photos from a camera - Camerawindow DC  ( [https://www.canon.co.uk/support/consumer_products/products/camcorders/digital/dc_series/dc10.aspx?type=download&language=&os=OS%20X%2010.10%20(Yosemite)](url) ) is disabled by colorfulSidebar9

Mac OS 10.10.5

In High Sierra I also had to remove the cDock bundle to get the camera download software to work.

**Comment by alwaysannoyed** [comment]
The Canon software for downloading photos from a camera - Camerawindow DC  ( [https://www.canon.co.uk/support/consumer_products/products/camcorders/digital/dc_series/dc10.aspx?type=download&language=&os=OS%20X%2010.10%20(Yosemite)](url) ) is disabled by colorfulSidebar9

**Comment by w0lfschild** [comment]
Probably best to disable loading into that app then.
