### ISSUE TITLE
cDock not working in Mojave

### ISSUE THREAD

**Issue by AdrenalineX** [w0lfschild/mySIMBL#97]
Love this app!! I miss the transparent and dimmed icons. Will you be updating to work with Mojave?

Thanks and keep up the great work!

**Comment by w0lfschild** [comment]
It does work on Mojave. System Integrity Protection must be disabled for it to run due to new security changes.

**Comment by AdrenalineX** [comment]
Ok, so System Integrity Protection just needs to be disabled so app can
load once and then I can re-enable SIP?

Warmest regards,

Scott Michaels




On Sep 26, 2018 at 9:15 AM, Wolfgang Baird <notifications@github.com>
wrote:


It should be working on Mojave. System Integrity Protection must be
disabled for plugins to load due to new security changes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/w0lfschild/mySIMBL/issues/97#issuecomment-424752947>,
or mute the thread

**Comment by npyl** [comment]
@AdrenalineX SIP needs to be disabled **permanently** on Mojave and later.
